services:
  - type: web
    name: waifu-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_WEBHOOK
        value: true
      - key: WEBHOOK_URL
        value: REPLACE_WITH_YOUR_RENDER_APP_URL
      - key: TELEGRAM_BOT_TOKEN
        value: REPLACE_WITH_YOUR_BOT_TOKEN
      - key: DATABASE_URL
        value: REPLACE_WITH_YOUR_DATABASE_URL
      - key: OWNER_ID
        value: REPLACE_WITH_YOUR_TELEGRAM_ID
      - key: CHANNEL_ID
        value: REPLACE_WITH_CHANNEL_ID
      - key: UPLOAD_GROUP_ID
        value: REPLACE_WITH_UPLOAD_GROUP_ID
      - key: GUESS_BOT_TOKEN
        value: REPLACE_WITH_GUESS_BOT_TOKEN